/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(Welcome)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(Welcome)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Welcome)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Welcome)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Welcome)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Welcome)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(Welcome)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(Welcome)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(Welcome)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(Welcome)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(Welcome)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(Welcome)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Welcome)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; };
    }
  }
}
